### ISSUE TITLE
ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by radheyshyamjat** [IslamKhSh/CardSlider#10]
```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.github.islamkhsh.CardSliderAdapter.instantiateItem(CardSliderAdapter.kt:50)
        at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter.instantiateItem(DelegatingPagerAdapter.java:53)
        at com.duolingo.open.rtlviewpager.RtlViewPager$ReversingAdapter.instantiateItem(RtlViewPager.java:338)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
        at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1086)
        at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
        at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
        at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter.superNotifyDataSetChanged(DelegatingPagerAdapter.java:148)
        at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter.access$100(DelegatingPagerAdapter.java:27)
        at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter$MyDataSetObserver.onChanged(DelegatingPagerAdapter.java:162)
        at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
        at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:294)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by IslamKhSh** [comment]
Fixed  e58af2ee39456321ec0869d73dcbf912ba1a63f7  (v1.0.0)
